### ISSUE TITLE
Backend database design

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#27]
I've tried to construct an excerpt of a faux database to illustrate how my ✨dream database✨ would probably look. It's a little hard to imagine exactly all the possible use case scenarios, but I've tried to incorporate a couple of scenarios to show how I'd expect the database to look in that situation haha! 

We'll probably have to keep refining this over testing because I'm sure there's going to be edge cases leading to the database design needing to be changed, but I think this is a good start?

Let's discuss soon!

<img width="1289" alt="Database_Draft" src="https://github.com/Gryphire/wisperbot/assets/17269537/d6888d4c-6701-447f-b9bc-1905e9c383b8">

**Comment by lydgate** [comment]
OK, one issue I can see is that we currently pair users with a `chat.name`, assumed to be unique. But in the above schema (and also in the code) it will be important to know the paired user's chat_id, so that messages can be passed between them. Also, it's possible that chat.names will not be unique I think?

Maybe there is a uid we could use to distinguish users unambiguously. The problem with using a `chat_id` is that we won't know the `chat_id`s until both users have started chats with the bot.

**Comment by lydgate** [comment]
OK, draft version of this done. Solved the above problem to do with `chat_id` of other user; will use a dictionary to track it while the bot is running. If it needs to persist, we might look at #39.

![image](https://github.com/Gryphire/wisperbot/assets/771/c5cbb989-42d2-43a5-bec9-01771960e1da)

```csv
timestamp,chat_id,sender,recver,recv_id,event,filename,status
2024-04-03 19:57:46.533860,5920741802,bot,bryan_kam,5920741802,send_vn,tutorialstories/tutstory1.ogg,tut_started
2024-04-03 19:57:50.629143,5920741802,bryan_kam,bot,5920741802,send_vn,20240403-18:57-Bryan-5920741802-AgADbxQAApOzcFA.ogg,tut_story2received
2024-04-03 19:57:50.689978,5920741802,bot,bryan_kam,5920741802,send_vn,tutorialstories/tutstory2.ogg,tut_story1responded
2024-04-03 19:58:03.380370,5920741802,bryan_kam,bot,5920741802,send_vn,20240403-18:58-Bryan-5920741802-AgADcRQAApOzcFA.ogg,tut_story2responded
```

**Comment by Gryphire** [comment]
Tried out the files on the corresponding branch but I get this error once I get to receiving a tutorial story:

2024-04-04 17:00:31,983 - chat-5625099873 - INFO - NastasiaGriffioen: Received first /gettutorialstory command
2024-04-04 17:00:32,053 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1264, in process_update
    await coroutine
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/Users/nastasia/surfdriveUT/wisperbot/echobot.py", line 136, in get_tutorial_story
    await chat.send_vn(f'tutorialstories/{tutorial_files[0]}')
  File "/Users/nastasia/surfdriveUT/wisperbot/chat.py", line 210, in send_vn
    await self.log_event(sender='bot',recver=self.name, recv_id='',event='send_vn',filename=VN)
  File "/Users/nastasia/surfdriveUT/wisperbot/chat.py", line 197, in log_event
    c.execute("INSERT INTO logs VALUES (?,?,?,?,?,?,?,?)",
sqlite3.OperationalError: table logs has 4 columns but 8 values were supplied

**Comment by Gryphire** [comment]
Removing earlier, existing database file in the directory resolved this issue.

Running till the very end, the /endtutorial command triggered this error (not sure if it's a bot-breaking one):

2024-04-04 17:43:33,867 - chat-5625099873 - INFO - NastasiaGriffioen: Status changing from "tut_story2responded" to "tut_completed"
2024-04-04 17:43:33,895 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1264, in process_update
    await coroutine
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/Users/nastasia/surfdriveUT/wisperbot/echobot.py", line 172, in tut_completed
    await chat.send_msg(f"Please send a voicenote introducing yourself to your partner, {chat.paired_user}!")
  File "/Users/nastasia/surfdriveUT/wisperbot/chat.py", line 180, in send_msg
    await self.context.bot.send_message(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 2820, in send_message
    return await super().send_message(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 541, in decorator
    result = await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 1015, in send_message
    return await self._send_message(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 581, in _send_message
    result = await super()._send_message(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 735, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 629, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 657, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 379, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 67

**Comment by lydgate** [comment]
Hi Nas,

I've pushed an update to the relevant branch that should make the logging much more verbose. All text sent and received as well as all voicenotes and commands should now get logged.

Would you be able to test?

The only thing that won't yet get logged to the database is if the bot skips steps to jump to a status or if the bot leaves a groupchat. Wasn't quite sure how to handle those within the database (if necessary).

Thanks,

Bryan
