### ISSUE TITLE
Get transcription working

### ISSUE THREAD

**Issue by lydgate** [Gryphire/wisperbot#3]
For now we'll try with OpenAI whisper

**Comment by lydgate** [comment]
I think this should be fixed in 1863183, could you test?

**Comment by Gryphire** [comment]
Recording a voice note now throws the following error, so no transcription takes place:

/bin/sh: ffmpeg: command not found
2023-06-08 11:00:56,948 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/Users/nastasia/Desktop/wisperbot/wisperbot_08062023.py", line 210, in get_voice
    transcript = await transcribe(update,filename)
  File "/Users/nastasia/Desktop/wisperbot/wisperbot_08062023.py", line 178, in transcribe
    subprocess.check_output(cmd, shell=True)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ffmpeg -i file:"files/private/Nastasia Griffioen-5625099873/20230608-11:00-Nastasia-AgAD7BIAAic3EVA.ogg" -c:a libopus -b:a 64k -af atempo=2 -y temp.webm' returned non-zero exit status 127.

**Comment by lydgate** [comment]
Is it possible for you to install [ffmpeg](http://ffmpeg.org/)? There is a small chance that you will also need to install libopus, but I expect that to be a requirement for ffmpeg.

Can you let me know your OS as well?

Just to explain, Telegram uses opus files but in an ogg container. OpenAI's Whisper API accepts opus but in webm format. So the format that comes out of Telegram cannot be sent "as is" to OpenAI.

Ffmpeg is a sort of swiss army knife of audio/video tools. It also allows us to double the transcription rate and therefore halve the cost.

**Comment by Gryphire** [comment]
Installation of ffmpeg to usr/local/bin successful, now following OpenAI error:

-------FOR CONTEXT-------
2023-06-08 14:28:36,503 - chat-5625099873 - INFO - Downloaded voicenote as files/private/Nastasia Griffioen-5625099873/20230608-14:28-Nastasia-AgADHRMAAic3EVA.ogg
ffmpeg version N-111016-gfa11c4c7fa-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 16.101 / 60. 16.101
  libavformat    60.  6.100 / 60.  6.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[ogg @ 0x7f7f440068c0] 729 bytes of comment header remain
Input #0, ogg, from 'file:files/private/Nastasia Griffioen-5625099873/20230608-14:28-Nastasia-AgADHRMAAic3EVA.ogg':
  Duration: 00:00:01.94, start: 0.000000, bitrate: 35 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, mono, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> opus (libopus))
Press [q] to stop, [?] for help
Output #0, webm, to 'temp.webm':
  Metadata:
    encoder         : Lavf60.6.100
  Stream #0:0: Audio: opus, 48000 Hz, mono, flt, 64 kb/s
    Metadata:
      encoder         : Lavc60.16.101 libopus
[out#0/webm @ 0x7f7f44007b40] video:0kB audio:8kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.205346%
size=       8kB time=00:00:00.95 bitrate=  72.6kbits/s speed=23.7x    
------ ERROR STARTS HERE ------
2023-06-08 14:28:41,129 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/Users/nastasia/Desktop/wisperbot/wisperbot_08062023.py", line 210, in get_voice
    transcript = await transcribe(update,filename)
  File "/Users/nastasia/Desktop/wisperbot/wisperbot_08062023.py", line 180, in transcribe
    transcript = openai.Audio.transcribe('whisper-1',audio_file).pop('text')
AttributeError: module 'openai' has no attribute 'Audio'
